/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:70fdfc35-f1f1-4bb9-99cb-ddc26fcdc0e7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TWxvlTomg",
    "aws_user_pools_web_client_id": "4imoesg6vh3gvjlsjgejggqhtu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5ylsruzmt5awfnbeuxgpvxv3iu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zxb4otzh5rgitlemvhvt2rbc4e",
    "aws_user_files_s3_bucket": "mybucketdeimagenes182717-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
